SewagePlantIMS/SewagePlantIMS/ViewModels/ShowElectrical.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SewagePlantIMS.ViewModels
{
    public class ShowElectrical
    {
        public int id { get; set; }
        public string technology_name { get; set; }
        public string elec_name { get; set; }
        public string remarks { get; set; }
        public string in_port { get; set; }
        public string out_port { get; set; }
        public string purpose { get; set; }
        public string pic_url { get; set; }
    }
}

SewagePlantIMS/SewagePlantIMS/Controllers/ElectricManageController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using SewagePlantIMS.Models;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
using System.Collections.Generic;
using System.IO;
using Gma.QrCodeNet.Encoding;
using Gma.QrCodeNet.Encoding.Windows.Render;
using System.Drawing.Imaging;
using System.Drawing;
using SewagePlantIMS.ViewModels;
using SewagePlantIMS.Function;
using SewagePlantIMS.Filter;
using System.Web.UI;

//Excel操作
using NPOI;
using NPOI.HSSF.UserModel;
using NPOI.XSSF.UserModel;
using NPOI.XSSF.Util;
using NPOI.SS.UserModel;
using NPOI.SS.Util;
namespace SewagePlantIMS.Controllers
{
    [LoginAttribute(isNeed = true)]
    public class ElectricManageController : Controller
    {
        /// <summary>
        /// 下面是仪表二维码的内容和方法
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ElectricalEquipment()
        {
            return View();
        }
        [HttpGet]
        public ActionResult AddElectrical()
        {
            List<technology> technologys = new List<technology>();
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            con.Open();
            string sqlStr = "select id,title from dm_technology;";
            SqlDataAdapter da = new SqlDataAdapter(sqlStr, con);
            DataSet ds = new DataSet();
            da.Fill(ds);
            technology[] tc = new technology[ds.Tables[0].Rows.Count];
            for (int mDr = 0; mDr < ds.Tables[0].Rows.Count; mDr++)
            {
                tc[mDr] = new technology();
                tc[mDr].id = Convert.ToInt32(ds.Tables[0].Rows[mDr][0]);
                tc[mDr].title = ds.Tables[0].Rows[mDr][1].ToString();

                technologys.Add(tc[mDr]);
            }
            con.Close();
            return View(technologys);
        }
        public JavaScriptResult AddElectrical_Post()
        {
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            con.Open();
            string selectID = "select id from dm_technology where title = '" + Request.Form["technology_name"] + "'";
            SqlCommand cmd2 = new SqlCommand(selectID, con);
            var id = cmd2.ExecuteScalar();
            string sqlStr = "insert into dm_electrical(technology_id,elec_name,remarks,in_port,out_port,purpose) values('" + id + "','" + Request.Form["elec_name"] + "','" + Request.Form["remarks"] + "','" + Request.Form["in_port"] + "','" + Request.Form["out_port"] + "','" + Request.Form["purpose"] + "');";
            SqlCommand cmd = new SqlCommand(sqlStr, con);
            int check = cmd.ExecuteNonQuery();
            con.Close();
            if (check == 1)
                return JavaScript("swal_success();jump_electrical_list();");
            else
                return JavaScript("swal_error();");
        }
        [HttpGet]
        public ActionResult Electrical_List()
        {
            List<Electrical> electrical = new List<Electrical>();

            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            con.Open();
            string sqlStr = "select id,elec_name from dm_electrical";
            SqlDataAdapter da = new SqlDataAdapter(sqlStr, con);
            DataSet ds = new DataSet();
            da.Fill(ds);
            Electrical[] E = new Electrical[ds.Tables[0].Rows.Count];
            for (int mDr = 0; mDr < ds.Tables[0].Rows.Count; mDr++)
            {
                E[mDr] = new Electrical();
                E[mDr].id = Convert.ToInt32(ds.Tables[0].Rows[mDr][0]);
                E[mDr].elec_name = ds.Tables[0].Rows[mDr][1].ToString();

                electrical.Add(E[mDr]);

                //直接生成二维码图片
                CreateQrCode(E[mDr].id, E[mDr].elec_name);
            }
            con.Close();
            return View(electrical);
        }


        public ActionResult DeleteElectrical()
        {
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            con.Open();
            //先删除对应的图片
            string del_pic = "select pic_url from dm_elec_pic where elec_id = " + Request.Form["del"];
            SqlDataAdapter da = new SqlDataAdapter(del_pic, con);
            DataSet ds = new DataSet();
            da.Fill(ds);
            for (int mDr = 0; mDr < ds.Tables[0].Rows.Count; mDr++)
            {

                string filePath = Server.MapPath(ds.Tables[0].Rows[mDr][0].ToString());
                FileInfo file2 = new FileInfo(filePath);
                if (file2.Exists)
                {
                    file2.Delete();
                }
            }
            //删除对应的二维码文件
            string del_qrcode = "select qrcode from dm_electrical where id = " + Request.Form["del"];
            SqlCommand cmd1 = new SqlCommand(del_qrcode, con);
            string url = Server.MapPath(cmd1.ExecuteScalar().ToString());
            FileInfo file = new FileInfo(url);
            file.Delete();

            //最后删除相应的数据库数据
            string sqlStr = "delete from dm_elec_pic where elec_id = " + Request.Form["del"] + "; delete from dm_electrical where id = " + Request.Form["del"] + ";";
            SqlCommand cmd = new SqlCommand(sqlStr, con);
            int check = cmd.ExecuteNonQuery();
            con.Close();
            return RedirectToAction("Electrical_List");
        }
        public ActionResult CreateQrCode(int id, string name)

        {
            string host = Request.Url.Host;
            var port = Request.Url.Port;

            string str = "http://" + host + ":" + port + "/ElectricManage/ShowElectrical?id=" + id;

            //向数据库中存入二维码图片地址
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            con.Open();

            using (var memoryStream = QRCodeHelper.GetQRCode(str, 10))
            {

                System.Drawing.Image img = Image.FromStream(memoryStream);
                string savePath = Server.MapPath("~/QRcode/ElectricQR/" + name + "temp.png");
                img.Save(savePath, ImageFormat.Png);

                AddTextToImg(savePath, name, name);
                img.Dispose();

                string sql = "update dm_electrical set qrcode = '" + "~/QRcode/ElectricQR/" + name + ".png' where id =" + id + ";";
                SqlCommand cmd = new SqlCommand(sql, con);
                int check = cmd.ExecuteNonQuery();
                con.Close();
                //img = Image.FromFile("~/QRcode/ElectricQR/" + name + ".png");
                //下面这段是将image转换为流从而输出到页面的img标签上去
                /*MemoryStream ms = new MemoryStream();
                byte[] imagedata = null;
                img.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg);
                imagedata = ms.GetBuffer();
                Response.ContentType = "image/jpeg";
                Response.OutputStream.Write(ms.GetBuffer(), 0, (int)ms.Length);
                Response.End();*/
            }
            con.Close();
            return null;
        }



        public class QRCodeHelper

        {

            /// <summary>  

            /// 生成二维码  

            /// </summary>  

            /// <param name="content">内容</param>

            /// <param name="moduleSize">二维码的大小</param>

            /// <returns>输出流</returns>  

            public static MemoryStream GetQRCode(string content, int moduleSize)

            {

                //ErrorCorrectionLevel 误差校正水平

                //QuietZoneModules     空白区域



                var encoder = new QrEncoder(ErrorCorrectionLevel.M);

                QrCode qrCode = encoder.Encode(content);

                GraphicsRenderer render = new GraphicsRenderer(new FixedModuleSize(moduleSize, QuietZoneModules.Two), Brushes.Black, Brushes.White);



                MemoryStream memoryStream = new MemoryStream();

                render.WriteToStream(qrCode.Matrix, ImageFormat.Jpeg, memoryStream);



                return memoryStream;



                //生成图片的代码

                //DrawingSize dSize = render.SizeCalculator.GetSize(qrCode.Matrix.Width);

                //Bitmap map = new Bitmap(dSize.CodeWidth, dSize.CodeWidth);

                //Graphics g = Graphics.FromImage(map);

                //render.Draw(g, qrCode.Matrix);

                //map.Save(fileName, ImageFormat.Jpeg);//fileName为存放的图片路径

            }



            /// <summary>

            /// 生成带Logo二维码  

            /// </summary>

            /// <param name="content">内容</param>

            /// <param name="iconPath">logo路径</param>

            /// <param name="moduleSize">二维码的大小</param>

            /// <returns>输出流</returns>

            public static MemoryStream GetQRCode(string content, string iconPath, int moduleSize = 9)

            {

                QrEncoder qrEncoder = new QrEncoder(ErrorCorrectionLevel.M);

                QrCode qrCode = qrEncoder.Encode(content);



                GraphicsRenderer render = new GraphicsRenderer(new FixedModuleSize(moduleSize, QuietZoneModules.Two), Brushes.Black, Brushes.White);



                DrawingSize dSize = render.SizeCalculator.GetSize(qrCode.Matrix.Width);

                Bitmap map = new Bitmap(dSize.CodeWidth, dSize.CodeWidth);

                Graphics g = Graphics.FromImage(map);

                render.Draw(g, qrCode.Matrix);



                //追加Logo图片 ,注意控制Logo图片大小和二维码大小的比例

                //PS:追加的图片过大超过二维码的容错率会导致信息丢失,无法被识别

                Image img = Image.FromFile(iconPath);

SewagePlantIMS/SewagePlantIMS/Views/ElectricManage/AddElectrical.cshtml
@model List<SewagePlantIMS.Models.technology>
@{
    ViewBag.Title = "添加电气信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.tag = "添加电气设备";
}
@using (Ajax.BeginForm("AddElectrical_Post", "ElectricManage", new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,

}))
{
    <fieldset>
        <legend style="color:#5b9bd1">基本信息</legend>
    </fieldset>
    <div class="am-form-group">
        <label for="elec_name">仪表名称</label>
        <input type="text" placeholder="请输入电气名称" class="form-control" name="elec_name">
    </div>

    <div class="am-form-group">
        <label for="name">所属工艺段</label>
        <select class="form-control" name="technology_name">
            @foreach (var item in Model)
            {
                <option>@item.title</option>
            }
        </select>
    </div>
    <div class="am-form-group">
        <label for="in_port">进线端</label>
        <input type="text" placeholder="请输入仪表进线端名称" class="form-control" name="in_port">
    </div>
    <div class="am-form-group">
        <label for="out_port">出线端</label>
        <input type="text" placeholder="请输入仪表出线端名称" class="form-control" name="out_port">
    </div>
    <div class="am-form-group">
        <label>用途</label>
        <textarea class="form-control" rows="4" name="purpose" placeholder="请输入仪表的用途"></textarea>
    </div>
    <div class="am-form-group">
        <label>添加备注</label>
        <textarea class="form-control" rows="4" name="remarks" placeholder="请输入其他相关的内容"></textarea>
    </div>
    <button type="submit" class="btn btn-primary btn-block">添加电气数据</button>

}
<button class="btn btn-default btn-block" onclick="javascrtpt:window.location.href='Electrical_List'">返回</button>

SewagePlantIMS/SewagePlantIMS/Views/ElectricManage/ElecReadingList.cshtml
@model List<SewagePlantIMS.ViewModels.ElectricReading>
@{
    ViewBag.Title = "电力巡查";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<fieldset>
    <legend style="color:#5b9bd1">电力巡查</legend>
</fieldset>
<a href="AddElecReading">新增抄表信息</a> &#47; <a href="AddElecReading">导出EXCEL表格</a>
<table class="table table-bordered table-hover table-striped" id="table_id_example">
    <thead>
        <tr>
            <th><input type="checkbox"/></th>
            <th>巡查时间</th>
            <th>巡查人</th>
            <th>备注</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td width="20px"><input type="checkbox" value="@item.total_id" name="check_id"/></td>
                <td>@item.add_time.ToLongDateString().ToString()</td>
                <td>@item.user_name</td>
                <td>@item.remark</td>
                <td>
                    @using (@Html.BeginForm("ModifyElectricReading", "ElectricManage", FormMethod.Post, new { @class = "myform" }))
                    {
                        <button class="btn btn-success btn-xs" type="submit" value="@item.total_id" name="erl_id">修改</button>
                    }
                    @using (@Html.BeginForm("DeleteElecReading", "ElectricManage", FormMethod.Post, new { @class = "myform" }))
                    {
                        <button class="btn btn-danger btn-xs" type="submit" value="@item.total_id" name="erl_del" id="erl_del" onclick="return confirm('确定删除吗？？？')">删除</button>
                    }
                    @using (@Html.BeginForm("ExcelElecReading", "ElectricManage", FormMethod.Post, new { @class = "myform" }))
                    {
                        <button class="btn btn-default btn-xs" type="submit" value="@item.total_id" name="erl_id" id="erl_excel" >Excel</button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

SewagePlantIMS/SewagePlantIMS/Views/ElectricManage/ElectricalEquipment.cshtml
@{
    ViewBag.Title = "ElectricalEquipment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ul id="myTab" class="nav nav-tabs">
    <li class="active">
        <a href="#list" data-toggle="tab">
            配电柜列表
        </a>
    </li>
    <li><a href="#ios" data-toggle="tab"></a></li>

</ul>
<div id="myTabContent" class="tab-content">
    <div class="tab-pane fade in active" id="list">
        <p></p>
    </div>
    <div class="tab-pane fade" id="ios">
        <p>
           
        </p>
    </div>
</div>

SewagePlantIMS/SewagePlantIMS/Views/ElectricManage/ElectricalPic.cshtml
@model List<SewagePlantIMS.Models.elec_pic>
@{
    ViewBag.Title = "添加电气图片";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">

    $(function () {
        $('#sub').click(function () {
            if ($("#filename").text() == '') {
                document.getElementById('fileerrorTip1').innerHTML = '您未选取任何需要要添加的图片！！';
                document.getElementById('fileerrorTip1').style.color = "red";
                return false;
            }
        });
    });
    /*function imgUrl() {
        document.getElementById("imgInit").src = "/images/ElectricalPic/电脑性能测试.png";
    }*/
</script>

<fieldset>
    <legend style="color:#5b9bd1">添加电气图片</legend>
</fieldset>
<div class="row">
    @foreach (var item in Model)
    {

        <div class="col-md-3">
            <div class="thumbnail">
                    <img src=@item.pic_url id="imgInit" onerror="imgUrl()" widht="100"  height="100" />
                

                <div class="caption">
                    @using (@Html.BeginForm("DeletePic", "ElectricManage", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                        <center><p><button href="" class="btn btn-danger" role="button" value=@item.id name="del_id">删除</button></p></center>
                    }
                </div>
            </div>
        </div>

    }
</div>

<hr />
@using (@Html.BeginForm("ElectricalPicPost", "ElectricManage", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <!--<input id="File1" type="file" name="File"/>-->
    <table>
        <tr>
            <td>
                <a class="input-file input-fileup" href="javascript:;">
                    + 选择文件<input size="100" type="file" name="file" id="file">
                </a>
            </td>
            <td>
                <button type="submit" value="@ViewBag.elec_id" name="id" class="btn btn-default btn-sm" id="sub">提交图片</button>
            </td>
        </tr>
    </table>

    <div class="fileerrorTip1" id="fileerrorTip1"></div>
    <div class="showFileName1" id="filename"></div>
    <input type="text" name="filename2" style="visibility: hidden;" id="filename2" />
}

SewagePlantIMS/SewagePlantIMS/Views/ElectricManage/Electrical_List.cshtml
@model List<SewagePlantIMS.Models.Electrical>
@{
    ViewBag.Title = "设备列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <fieldset>
        <legend style="color:#5b9bd1">仪表列表</legend>
    </fieldset>

    <a href="AddElectrical">新增仪表信息</a>
    <table class="table table-bordered table-hover table-striped" id="table_id_example">
        <thead>
            <tr>
                <th>序号</th>
                <th>名称</th>
                <th>相关操作</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.id </td>
                    <td>@item.elec_name</td>

                    <td>
                        @using (@Html.BeginForm("ModifyElectrical", "ElectricManage", FormMethod.Post, new { @class = "myform" }))
                        {
                            <button class="btn btn-success btn-xs" type="submit" value="@item.id" name="id">修改</button>
                        }
                        @using (@Html.BeginForm("ElectricalPic", "ElectricManage", FormMethod.Post, new { @class = "myform" }))
                        {
                            <button class="btn btn-primary btn-xs" type="submit" value="@item.id" name="id">添加图片</button>
                        }
                        @using (@Html.BeginForm("DeleteElectrical", "ElectricManage", FormMethod.Post, new { @class = "myform" }))
                        {
                            <button class="btn btn-danger btn-xs" type="submit" value="@item.id" name="del" id="del" onclick="return confirm('确定删除吗？？？')">删除</button>
                        }
                        @using (@Html.BeginForm("ShowElectrical", "ElectricManage", FormMethod.Post, new { @class = "myform" }))
                        {
                            <button class="btn btn-default btn-xs" value="@item.id" name="show">展示页</button>
                        }
                        @using (@Html.BeginForm("DownloadQRcode", "ElectricManage", FormMethod.Post, new { @class = "myform" }))
                        {
                            <button class="btn btn-warning btn-xs" value="@item.elec_name" name="qrcode" type="submit">二维码</button>
                        }
                    </td>
                </tr>
            }

        </tbody>

    </table>




</div>

SewagePlantIMS/SewagePlantIMS/Views/ElectricManage/Index.cshtml
@{
    ViewBag.Title = "瓯江口污水处理厂";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

SewagePlantIMS/SewagePlantIMS/Views/ElectricManage/ModifyElectrical.cshtml
@model SewagePlantIMS.Models.Electrical

@{
    ViewBag.Title = "修改仪表信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Ajax.BeginForm("ModifyElectricl_Post", "ElectricManage", new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,

}))
{
    <fieldset>
        <legend style="color:#5b9bd1">修改基本信息</legend>
    </fieldset>
    <div class="am-form-group">
        <label for="elec_name">仪表名称</label>
        <input type="text" placeholder="请输入电气名称" class="form-control" name="elec_name" value=@Model.elec_name>
    </div>

    <div class="am-form-group">
        <label for="name">所属工艺段</label>
        <select class="form-control" name="technology_name">
            @foreach (var item in ViewBag.List)
            {
                if (!@item.Equals(@Model.technology_name))
                {
                    <option>@item</option>
                }
                else
                {
                    <option selected>@item</option>
                }
            }
        </select>
    </div>
    <div class="am-form-group">
        <label for="in_port">进线端</label>
        <input type="text" placeholder="请输入仪表进线端名称" class="form-control" name="in_port" value=@Model.in_port>
    </div>
    <div class="am-form-group">
        <label for="out_port">出线端</label>
        <input type="text" placeholder="请输入仪表出线端名称" class="form-control" name="out_port" value=@Model.out_port>
    </div>
    <div class="am-form-group">
        <label>用途</label>
        <textarea class="form-control" rows="4" name="purpose" placeholder="请输入仪表的用途">@Model.purpose</textarea>
    </div>
    <div class="am-form-group">
        <label>添加备注</label>
        <textarea class="form-control" rows="4" name="remarks" placeholder="请输入其他相关的内容">@Html.Raw(Model.remarks)</textarea>
    </div>
    <button type="submit" class="btn btn-primary btn-block">修改</button>

}
<button class="btn btn-default btn-block" onclick="javascrtpt:window.location.href='Electrical_List'">返回</button>

SewagePlantIMS/SewagePlantIMS/Views/ElectricManage/ShowElectrical.cshtml
@model List<SewagePlantIMS.ViewModels.ShowElectrical>
@{
    Layout = null;
    int i = 0;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>瓯江口污水厂仪表</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


    <style>
        .carousel .item {
            height: 400px;
            background-color: #777;
        }

        .carousel-inner > .item > img {
            position: absolute;
            top: 0;
            left: 0;
            min-width: 100%;
            height: 400px;
        }
    </style>
</head>
<body>

    <div id="myCarousel" class="carousel slide">

        <div class="carousel-inner">
            @foreach (var item in Model)
            {
                if (@i == 0)
                {
                    <div class="item active">
                        <img src=@item.pic_url onclick="showMaxImg(this)">
                    </div>
                }
                else
                {
                    <div class="item">
                        <img src=@item.pic_url onclick="showMaxImg(this)">
                    </div>
                }
                i++;
            }

        </div>
        <!-- 轮播（Carousel）导航 -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    @foreach (var item in Model)
    {
        <table class="table">
            <tr>
                <td style="width:100px">仪表名称：</td>
                <td>@item.elec_name</td>
            </tr>
            <tr>
                <td>所在工艺段：</td>
                <td>@item.technology_name</td>
            </tr>
            <tr>
                <td>进线端：</td>
                <td>@item.in_port</td>
            </tr>
            <tr>
                <td>出线端：</td>
                <td>@item.out_port</td>
            </tr>
            <tr>
                <td>用途：</td>
                <td>@item.purpose</td>
            </tr>
            <tr>
                <td>备注：</td>
                <td>@Html.Raw(item.remarks)</td>
            </tr>
        </table>
        break;
    }
    <div class="modal fade bs-example-modal-lg text-center" id="imgModal" tabindex="-1" role="dialog" data-toggle="modal" aria-labelledby="myLargeModalLabel" aria-hidden="true">   <div class="modal-dialog modal-lg" style="display:inline-block;width:auto;">       <div class="modal-content">           <div id="imgshow"></div>        </div>      </div>    </div>

</body>
</html>

<script>
    $(function () {
        $('#myCarousel').carousel({
            interval: 3000
        });
    });
    function showMaxImg(obj) { var src = $(obj).attr("src"); $("#imgModal").find("#imgshow").html("<img src='" + src + "' class='carousel-inner img-responsive img-rounded' data-dismiss='modal'>"); $("#imgModal").modal('show'); }

</script>