SewagePlantIMS/SewagePlantIMS/Models/Device.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SewagePlantIMS.Models
{
    public class Device
    {
        public int id { get; set; }
        [Display(Name = "工艺段")]
        public int technology_id { get; set; }
        [Display(Name = "设备类别")]
        public int class_id { get; set; }
        [Display(Name = "设备名称")]
        public string title { get; set; }
        [Display(Name = "主要参数")]
        public string summary { get; set; }
        [Display(Name = "设备状态")]
        public int state { get; set; }
        [Display(Name = "添加时间")]
        public DateTime add_date { get; set; }
        [Display(Name = "添加的用户ID")]
        public int add_user_id { get; set; }
        [Display(Name = "添加的用户名")]
        public string add_user_name { get; set; }
        public string pic_src { get; set; }
        [Display(Name = "设备别名")]
        public string alias { get; set; }
        [Display(Name = "安装日期")]
        public DateTime? purchase_date { get; set; }
        [Display(Name = "品牌ID")]
        public int brand_id { get; set; }
        [Display(Name = "型号")]
        public string device_model { get; set; }
        [Display(Name = "功率")]
        public string device_power { get; set; }
        public string qrcode { get; set; }

    }
}

SewagePlantIMS/SewagePlantIMS/Models/DeviceMaintenance.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SewagePlantIMS.Models
{
    public class DeviceMaintenance
    {
        public int id { get; set; }
        [Display(Name = "设备名称")]
        public int device_id { get; set; }
        public int user_id { get; set; }
        [Display(Name = "保养内容")]
        public string dm_content { get; set; }
        [Display(Name = "物品使用")]
        public string dm_consumption { get; set; }
        [Display(Name = "保养进度")]
        public int dm_isfinish { get; set; }
        [Display(Name = "保养时间")]
        public DateTime dm_date { get; set; }
        [Display(Name = "保养周")]
        public int dm_weekend { get; set; }
        [Display(Name = "是否额外")]
        public int dm_isextra { get; set; }
        [Display(Name = "备注")]
        public string remark { get; set; }

    }
}

SewagePlantIMS/SewagePlantIMS/Models/DeviceMaintenancePlan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SewagePlantIMS.Models
{
    public class DeviceMaintenancePlan
    {
        public int id { get; set; }
        [Display(Name = "设备名称")]
        public int device_id { get; set; }
        public int user_id { get; set; }
        public int order_id { get; set; }
        [Display(Name = "保养内容")]
        public string dmp_content { get; set; }
        [Display(Name = "物品使用")]
        public string dmp_consumption { get; set; }
        [Display(Name = "保养进度")]
        public int dmp_isfinish { get; set; }
        [Display(Name = "保养月份")]
        public int dmp_month { get; set; }
        [Display(Name = "保养周")]
        public int dmp_weekend { get; set; }
        [Display(Name = "备注")]
        public string remark { get; set; }

    }
}

SewagePlantIMS/SewagePlantIMS/Models/DeviceRepair.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SewagePlantIMS.Models
{
    public class DeviceRepair
    {
        public int id { get; set; }
        [Display(Name = "设备名称")]
        public int device_id { get; set; }
        [Display(Name = "用户")]
        public int user_id { get; set; }
        [Display(Name = "工艺段")]
        public int technology_id { get; set; }
        [Display(Name = "维修日期")]
        public DateTime repair_date { get; set; }
        [Display(Name = "完工日期")]
        public DateTime repair_finsh { get; set; }
        [Display(Name = "维修类别")]
        public string repair_class { get; set; }
        [Display(Name = "维修设备详名")]
        public string repair_title { get; set; }
        [Display(Name = "维修设备数量")]
        [Range(typeof(decimal), "0.00", "99999999.99", ErrorMessage = "输入的数据不正确！")]
        [RegularExpression(@"^(([0-9]+)|([0-9]+\.[0-9]{1,2}))$", ErrorMessage = "输入的数据不正确！")]
        public int repair_nums { get; set; }
        [Display(Name = "维修原因")]
        public string repair_reasons { get; set; }
        [Display(Name = "维修结论")]
        public string repair_conclusion { get; set; }
        [Display(Name = "参与维修的人员")]
        public string repair_join { get; set; }
        [Display(Name = "零部件消耗情况")]
        public string repair_consumption { get; set; }
        [Display(Name = "备注")]
        public string repair_mark { get; set; }
        [Display(Name = "故障/改造时间")]
        public DateTime repair_begin { get; set; }
        [Display(Name = "预计开工时间")]
        public DateTime repair_starts { get; set; }
        [Display(Name = "预计耗时(小时)")]
        [Range(typeof(decimal), "0.00", "99999999.99", ErrorMessage = "输入的数据不正确！")]
        [RegularExpression(@"^(([0-9]+)|([0-9]+\.[0-9]{1,2}))$", ErrorMessage = "输入的数据不正确！")]
        public double repair_consume { get; set; }
        [Display(Name = "经理意见")]
        public string manager_opinion { get; set; }
        [Display(Name = "是否审批")]
        public int isapproval { get; set; }
        [Display(Name = "是否完工")]
        public int isover { get; set; }
    }
}

SewagePlantIMS/SewagePlantIMS/Models/DeviceRepairPic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SewagePlantIMS.Models
{
    public class DeviceRepairPic
    {
        public int id { get; set; }
        [Display(Name = "图片名称")]
        public string title { get; set; }
        [Display(Name = "图片存放地址")]
        public string pic_url { get; set; }
        [Display(Name = "图片描述")]
        public string describe { get; set; }
        [Display(Name = "添加时间")]
        public DateTime add_date { get; set; }
        [Display(Name = "对应的设备维修")]
        public int repair_id { get; set; }
        [Display(Name = "图片类型")]
        public int type { get; set; }

    }
}

SewagePlantIMS/SewagePlantIMS/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SewagePlantIMS.Filter;
using SewagePlantIMS.Function;
using SewagePlantIMS.Models;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
using System.IO;
using System.Drawing;
//为了将SQL数据转为JSON数据而引用的
using Newtonsoft.Json;
using System.Text;
using Newtonsoft.Json.Linq;
//Excel操作
using NPOI;
using NPOI.HSSF.UserModel;
using NPOI.XSSF.UserModel;
using NPOI.XSSF.Util;
using NPOI.SS.UserModel;
using NPOI.SS.Util;




namespace SewagePlantIMS.Controllers
{
    [LoginAttribute(isNeed = true)]
    public class DeviceController : Controller
    {
        // GET: Device
        //设备列表呈现
        public ActionResult DeviceList()
        {
            List<Device> model = new List<Device>();

            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            con.Open();
            string sqlStr = "select id,technology_id,class_id,title,brand_id from dm_device;";
            SqlDataAdapter da = new SqlDataAdapter(sqlStr, con);
            DataSet ds = new DataSet();
            da.Fill(ds);
            Device[] E = new Device[ds.Tables[0].Rows.Count];
            for (int mDr = 0; mDr < ds.Tables[0].Rows.Count; mDr++)
            {
                E[mDr] = new Device();
                E[mDr].id = Convert.ToInt32(ds.Tables[0].Rows[mDr][0]);
                E[mDr].technology_id = Convert.ToInt32(ds.Tables[0].Rows[mDr][1]);
                E[mDr].class_id = Convert.ToInt32(ds.Tables[0].Rows[mDr][2]);
                E[mDr].title = ds.Tables[0].Rows[mDr][3].ToString();
                E[mDr].brand_id = Convert.ToInt32(ds.Tables[0].Rows[mDr][4]);
                model.Add(E[mDr]);
            }

            List<string> technology_name = new List<string>();
            List<string> class_name = new List<string>();
            List<string> brand_name = new List<string>();
            SqlCommand cmd = new SqlCommand();
            foreach (var data in model)
            {
                sqlStr = "select title from dm_technology where id = " + data.technology_id + ";";
                cmd = new SqlCommand(sqlStr, con);
                technology_name.Add(cmd.ExecuteScalar().ToString());
                sqlStr = "select title from dm_device_class where id = " + data.class_id + ";";
                cmd = new SqlCommand(sqlStr, con);
                class_name.Add(cmd.ExecuteScalar().ToString());
                sqlStr = "select title from dm_supplier_brand where id = " + data.brand_id + ";";
                cmd = new SqlCommand(sqlStr, con);
                brand_name.Add(cmd.ExecuteScalar().ToString());
            }
            ViewBag.technology_name = technology_name;
            ViewBag.class_name = class_name;
            ViewBag.brand_name = brand_name;
            con.Close();
            return View(model);
        }
        //新增设备信息
        public ActionResult AddDevice()
        {
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            con.Open();
            //1)查出所有分类
            string sqlStr = "select id,title from dm_device_class where id not in (select distinct parent_id from dm_device_class);";
            SqlDataAdapter da = new SqlDataAdapter(sqlStr, con);
            DataSet ds = new DataSet();
            da.Fill(ds);
            List<SelectListItem> list_class = new List<SelectListItem>();
            for (int mDr = 0; mDr < ds.Tables[0].Rows.Count; mDr++)
            {
                list_class.Add(new SelectListItem() { Value = "" + ds.Tables[0].Rows[mDr][0].ToString() + "", Text = "" + ds.Tables[0].Rows[mDr][1].ToString() + "" });
            }
            ViewBag.list_class = list_class;
            //2)查出所有工艺段
            sqlStr = "select id,title from dm_technology;";
            da = new SqlDataAdapter(sqlStr, con);
            ds = new DataSet();
            da.Fill(ds);
            List<SelectListItem> list_tecnology = new List<SelectListItem>();
            for (int mDr = 0; mDr < ds.Tables[0].Rows.Count; mDr++)
            {
                list_tecnology.Add(new SelectListItem() { Value = "" + ds.Tables[0].Rows[mDr][0].ToString() + "", Text = "" + ds.Tables[0].Rows[mDr][1].ToString() + "" });
            }
            ViewBag.list_tecnology = list_tecnology;
            //3)查出所有的品牌
            sqlStr = "select id,title from dm_supplier_brand;";
            da = new SqlDataAdapter(sqlStr, con);
            ds = new DataSet();
            da.Fill(ds);
            List<SelectListItem> list_brand = new List<SelectListItem>();
            for (int mDr = 0; mDr < ds.Tables[0].Rows.Count; mDr++)
            {
                list_brand.Add(new SelectListItem() { Value = "" + ds.Tables[0].Rows[mDr][0].ToString() + "", Text = "" + ds.Tables[0].Rows[mDr][1].ToString() + "" });
            }
            ViewBag.list_brand = list_brand;
            //4)设置一下状态
            List<SelectListItem> state = new List<SelectListItem>();
            state.Add(new SelectListItem() { Value = "1", Text = "正常" });
            state.Add(new SelectListItem() { Value = "0", Text = "异常" });
            ViewBag.state = state;
            con.Close();
            return View();
        }
        //提交设备信息
        [HttpPost]
        public JavaScriptResult AddDevice_post(Device model)
        {
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            con.Open();
            string sqlStr = "insert into dm_device(title,alias,class_id,technology_id,brand_id,state,device_power,device_model,summary,purchase_date,add_date,add_user_id,add_user_name) values('" + model.title + "','" + model.alias + "'," + model.class_id + "," + model.technology_id + "," + model.brand_id + "," + model.state + ",'" + model.device_power + "','" + model.device_model + "','" + model.summary + "','" + model.purchase_date + "','" + DateTime.Now + "'," + Session["user_id"] + ",'" + Session["real_name"] + "')";
            SqlCommand cmd = new SqlCommand(sqlStr, con);
            int check = cmd.ExecuteNonQuery();
            con.Close();
            if (check == 1)
                return JavaScript("swal_success();jump_DeviceList();");
            else
                return JavaScript("swal_error();");
        }
        //修改设备信息
        public ActionResult ModifyDevice()
        {
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            con.Open();
            Device model = new Device();
            //0)查出当前设备的信息
            string sqlinfo = "select id,title,alias,class_id,technology_id,brand_id,state,device_power,device_model,summary,purchase_date from dm_device where id = " + Request.Form["id"] + ";";
            SqlCommand cmd = new SqlCommand(sqlinfo, con);
            SqlDataReader reader = cmd.ExecuteReader();
            while (reader.Read())    // 判断数据是否读到尾. 
            {
                model.id = Convert.ToInt32(reader["id"]);
                model.title = reader["title"].ToString();
                model.alias = reader["alias"].ToString();
                model.class_id = Convert.ToInt32(reader["class_id"]);
                model.technology_id = Convert.ToInt32(reader["technology_id"]);
                model.brand_id = Convert.ToInt32(reader["brand_id"]);
                model.state = Convert.ToInt32(reader["state"]);
                model.device_power = reader["device_power"].ToString();
                model.device_model = reader["device_model"].ToString();
                model.summary = reader["summary"].ToString();
                if (reader["purchase_date"] != DBNull.Value) model.purchase_date = Convert.ToDateTime(reader["purchase_date"]);   //特殊情况
            }
            reader.Close();
            //1)查出所有分类
            string sqlStr = "select id,title from dm_device_class where id not in (select distinct parent_id from dm_device_class);";
            SqlDataAdapter da = new SqlDataAdapter(sqlStr, con);
            DataSet ds = new DataSet();
            da.Fill(ds);
            List<SelectListItem> list_class = new List<SelectListItem>();
            for (int mDr = 0; mDr < ds.Tables[0].Rows.Count; mDr++)
            {
                list_class.Add(new SelectListItem() { Value = "" + ds.Tables[0].Rows[mDr][0].ToString() + "", Text = "" + ds.Tables[0].Rows[mDr][1].ToString() + "" });
            }
            ViewBag.list_class = list_class;
            //2)查出所有工艺段
            sqlStr = "select id,title from dm_technology;";
            da = new SqlDataAdapter(sqlStr, con);
            ds = new DataSet();
            da.Fill(ds);
            List<SelectListItem> list_tecnology = new List<SelectListItem>();
            for (int mDr = 0; mDr < ds.Tables[0].Rows.Count; mDr++)
            {
                list_tecnology.Add(new SelectListItem() { Value = "" + ds.Tables[0].Rows[mDr][0].ToString() + "", Text = "" + ds.Tables[0].Rows[mDr][1].ToString() + "" });
            }
            ViewBag.list_tecnology = list_tecnology;
            //3)查出所有的品牌
            sqlStr = "select id,title from dm_supplier_brand;";
            da = new SqlDataAdapter(sqlStr, con);
            ds = new DataSet();
            da.Fill(ds);
            List<SelectListItem> list_brand = new List<SelectListItem>();
            for (int mDr = 0; mDr < ds.Tables[0].Rows.Count; mDr++)
            {
                list_brand.Add(new SelectListItem() { Value = "" + ds.Tables[0].Rows[mDr][0].ToString() + "", Text = "" + ds.Tables[0].Rows[mDr][1].ToString() + "" });
            }
            ViewBag.list_brand = list_brand;
            //4)设置一下状态
            List<SelectListItem> state = new List<SelectListItem>();
            state.Add(new SelectListItem() { Value = "1", Text = "正常" });

SewagePlantIMS/SewagePlantIMS/Views/Device/AddDeviceMaintenance.cshtml
@model SewagePlantIMS.Models.DeviceMaintenance
@{
    ViewBag.Title = "新增本月保养内容";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<fieldset>
    <legend style="color:#5b9bd1">增加本月额外保养</legend>
</fieldset>


@using (Ajax.BeginForm("AddDeviceMaintenance_Post", "Device", new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,

}))
{
    <div class="am-form-group">
        @Html.LabelFor(model => model.device_id, htmlAttributes: new { @class = "control-label" })
        @Html.DropDownListFor(model => model.device_id, new SelectList(ViewBag.list_device, "Value", "Text"), new { @class = "btn btn-default dropdown-toggle form-control", @onchange = "selectOnchang(this)" })
    </div>
        <div class="am-form-group">
            @Html.LabelFor(model => model.dm_content, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.dm_content, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入保养内容" } })
            @Html.ValidationMessageFor(model => model.dm_content, "", new { @class = "text-danger" })
        </div>
        <div class="am-form-group">
            @Html.LabelFor(model => model.dm_consumption, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.dm_consumption, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入保养内容" } })
            @Html.ValidationMessageFor(model => model.dm_consumption, "", new { @class = "text-danger" })
        </div>
        <div class="am-form-group">
            @Html.LabelFor(model => model.dm_date, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.dm_date, new { htmlAttributes = new { @class = "form-control" ,@type = "date" } })
            @Html.ValidationMessageFor(model => model.dm_date, "", new { @class = "text-danger" })
        </div>
        <div class="am-form-group">
            @Html.LabelFor(model => model.dm_weekend, htmlAttributes: new { @class = "control-label" })
            @Html.DropDownListFor(model => model.dm_weekend, new SelectList(ViewBag.weekend, "Value", "Text"), new { @class = "btn btn-default dropdown-toggle form-control", @onchange = "selectOnchang(this)" })
        </div>
        <div class="am-form-group">
            @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入相关备注" } })
            @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
        </div>
        <button type="submit" class="btn btn-primary btn-block">新增保养</button>
}

<button class="btn btn-default btn-block" onclick="javascrtpt: window.location.href = 'DeviceMaintenance'">返回</button>

SewagePlantIMS/SewagePlantIMS/Views/Device/AddDeviceMaintenancePlan.cshtml
@model SewagePlantIMS.Models.DeviceMaintenancePlan
@{
    ViewBag.Title = "新增保养计划";
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link rel="stylesheet" href="~/assets/libs/layui/css/layui.css" />
<link rel="stylesheet" href="~/assets/module/admin.css?v=312" />
<!--没有下面两个JS则后台javascript返回失效-->
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<!-- js部分 -->
<script type="text/javascript" src="~/assets/libs/layui/layui.js"></script>
<script type="text/javascript" src="~/assets/js/common.js?v=312"></script>
<script src="/static/build/layui.js"></script>
<!--没有它就无法执行双击行弹出内容，高亮等功能-->
<script src="~/Scripts/DataTableExtend.js"></script>
<!--设置弹窗用-->
<script>
layui.use('layer', function(){ //独立版的layer无需执行这一句
  var $ = layui.jquery, layer = layui.layer; //独立版的layer无需执行这一句

  //触发事件
  var active = {
    setTop: function(){
      var that = this;
      //多窗口模式，层叠置顶
      layer.open({
        type: 2 //此处以iframe举例
        ,title: '当你选择该窗体时，即会在最顶端'
        ,area: ['390px', '260px']
        ,shade: 0
        ,maxmin: true
        ,offset: [ //为了演示，随机坐标
          Math.random()*($(window).height()-300)
          ,Math.random()*($(window).width()-390)
        ]
        ,content: '//layer.layui.com/test/settop.html'
        ,btn: ['继续弹出', '全部关闭'] //只是为了演示
        ,yes: function(){
          $(that).click();
        }
        ,btn2: function(){
          layer.closeAll();
        }

        ,zIndex: layer.zIndex //重点1
        ,success: function(layero){
          layer.setTop(layero); //重点2
        }
      });
    }
    ,confirmTrans: function(){
      //配置一个透明的询问框
      layer.msg('大部分参数都是可以公用的<br>合理搭配，展示不一样的风格', {
        time: 20000, //20s后自动关闭
        btn: ['明白了', '知道了', '哦']
      });
    }
    
  };

  $('#layerDemo .layui-btn').on('click', function(){
    var othis = $(this), method = othis.data('method');
    active[method] ? active[method].call(this, othis) : '';
  });

});
</script>
<div style="margin:10px 10px 10px 10px">
    <fieldset>
        <legend style="color:#5b9bd1">新增保养计划</legend>
        <blockquote class="layui-elem-quote layui-quote-nm">
            <div class="site-demo-button" id="layerDemo" style="margin-bottom: 0;">
                <a class="layui-btn" data-method="confirmTrans">EXCEL模板下载</a>
            </div>
            <h4 style="padding:5px;">导入保养计划</h4><div class="layui-upload"><button type="button" class="layui-btn layui-btn-normal" id="test8">选择文件</button><button type="button" class="layui-btn" id="test9">开始上传</button></div>
        </blockquote>
        
    </fieldset>
    

    @using (Ajax.BeginForm("AddDeviceMaintenancePlan_Post", "Device", new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,

    }))
    {
        <div class="am-form-group">
            @Html.LabelFor(model => model.device_id, htmlAttributes: new { @class = "control-label" })
            @Html.DropDownListFor(model => model.device_id, new SelectList(ViewBag.list_device, "Value", "Text"), new { @class = "btn btn-default dropdown-toggle form-control", @onchange = "selectOnchang(this)" })
        </div>
        <div class="am-form-group">
            @Html.LabelFor(model => model.dmp_content, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.dmp_content, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入保养内容" } })
            @Html.ValidationMessageFor(model => model.dmp_content, "", new { @class = "text-danger" })
        </div>
        <div class="am-form-group">
            @Html.LabelFor(model => model.dmp_consumption, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.dmp_consumption, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入保养内容" } })
            @Html.ValidationMessageFor(model => model.dmp_consumption, "", new { @class = "text-danger" })
        </div>
        <div class="am-form-group">
            @Html.LabelFor(model => model.dmp_month, htmlAttributes: new { @class = "control-label" })
            @Html.DropDownListFor(model => model.dmp_month, new SelectList(ViewBag.month, "Value", "Text"), new { @class = "btn btn-default dropdown-toggle form-control", @onchange = "selectOnchang(this)" })
        </div>
        <div class="am-form-group">
            @Html.LabelFor(model => model.dmp_weekend, htmlAttributes: new { @class = "control-label" })
            @Html.DropDownListFor(model => model.dmp_weekend, new SelectList(ViewBag.weekend, "Value", "Text"), new { @class = "btn btn-default dropdown-toggle form-control", @onchange = "selectOnchang(this)" })
        </div>
        <div class="am-form-group">
            @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入相关备注" } })
            @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
        </div>
        <button type="submit" class="btn btn-primary btn-block">添加保养计划</button>
    }

    <button class="btn btn-default btn-block" onclick="javascrtpt: window.location.href = 'DeviceMaintenancePlan'">返回</button>


</div>
<!--导入excel用-->
<script>
layui.use('upload', function(){
  var $ = layui.jquery
  ,upload = layui.upload;


  //选完文件后不自动上传
  upload.render({
    elem: '#test8'
    , url: '/Device/InputDeviceMaintenancePlan'
    , auto: false
    , accept: 'file' //普通文件
    , exts: 'xls' //只允许上传xls结尾的excel文件
    //,multiple: true
    ,bindAction: '#test9'
    ,done: function(res){
        console.log(res);
        console.log(res.code);
    }
  });

  

});
</script>

SewagePlantIMS/SewagePlantIMS/Views/Device/AddDevicePic.cshtml
@model List<SewagePlantIMS.Models.DevicePic>
@{
    ViewBag.Title = "添加设备图片";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">

    $(function () {
        $('#sub').click(function () {
            if ($("#filename").text() == '') {
                document.getElementById('fileerrorTip1').innerHTML = '您未选取任何需要要添加的图片！！';
                document.getElementById('fileerrorTip1').style.color = "red";
                return false;
            }
        });
    });
    /*function imgUrl() {
        document.getElementById("imgInit").src = "/images/ElectricalPic/电脑性能测试.png";
    }*/
</script>

<fieldset>
    <legend style="color:#5b9bd1">添加设备图片<button class="btn btn-default btn-xs" onclick="javascrtpt: window.location.href = 'DeviceList'">返回</button></legend>
</fieldset>
<div class="row">
    @foreach (var item in Model)
    {

        <div class="col-md-3">
            <div class="thumbnail">
                <img src=@item.pic_url id="imgInit" onerror="imgUrl()" height="100" />
                <div class="caption">
                    @using (@Html.BeginForm("DeleteDevicePic", "Device", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <center><p><button href="" class="btn btn-danger" role="button" value=@item.id name="del_id" onclick="return confirm('确定删除吗？？？')">删除</button></p></center>
                    }
                </div>
            </div>
        </div>

    }
</div>

<hr />
@using (@Html.BeginForm("AddDevicePicPost", "Device", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <!--<input id="File1" type="file" name="File"/>-->
    <table>
        <tr>
            <td>
                <a class="input-file input-fileup" href="javascript:;">
                    + 选择文件<input size="100" type="file" name="file" id="file">
                </a>
            </td>
            <td>
                <button type="submit" value="@ViewBag.id" name="id" class="btn btn-default btn-sm" id="sub">提交图片</button>
            </td>
        </tr>
    </table>

    <div class="fileerrorTip1" id="fileerrorTip1"></div>
    <div class="showFileName1" id="filename"></div>
    <input type="text" name="filename2" style="visibility: hidden;" id="filename2" />
}