SewagePlantIMS/SewagePlantIMS/ViewModels/ShowChemicalDevice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SewagePlantIMS.ViewModels
{
    public class ShowChemicalDevice
    {
        public int id { get; set; }
        [Display(Name = "仪器名称")]
        public string cd_name { get; set; }
        [Display(Name = "型号")]
        public string cd_model { get; set; }
        [Display(Name = "数量")]
        [Range(typeof(decimal), "0.00", "99999999.99", ErrorMessage = "输入的数据格式不正确！")]
        public int cd_quantity { get; set; }
        [Display(Name = "编号")]
        public string cd_num { get; set; }
        [Display(Name = "厂家")]
        public string cd_manufacturer { get; set; }
        [Display(Name = "保管人")]
        public string cd_preserver { get; set; }
        [Display(Name = "启用时间")]
        [DataType(DataType.DateTime)]
        public DateTime cd_begin_time { get; set; }
        [Display(Name = "备注")]
        [DataType(DataType.MultilineText)]
        public string cd_remark { get; set; }
        public string cd_picurl { get; set; }

    }
}

SewagePlantIMS/SewagePlantIMS/Controllers/ChemicalController.cs
using SewagePlantIMS.Filter;
using SewagePlantIMS.Function;
using SewagePlantIMS.Models;
using SewagePlantIMS.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace SewagePlantIMS.Controllers
{
    [LoginAttribute(isNeed = true)]
    public class ChemicalController : Controller
    {
        // GET: Chemical
        public ActionResult ChemicalDeviceList()
        {
            List<chemical_device> model = new List<chemical_device>();

            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            con.Open();
            string sqlStr = "select id,cd_manufacturer,cd_name,cd_preserver from dm_chemical_device;";
            SqlDataAdapter da = new SqlDataAdapter(sqlStr, con);
            DataSet ds = new DataSet();
            da.Fill(ds);
            chemical_device[] E = new chemical_device[ds.Tables[0].Rows.Count];
            for (int mDr = 0; mDr < ds.Tables[0].Rows.Count; mDr++)
            {
                E[mDr] = new chemical_device();
                E[mDr].id = Convert.ToInt32(ds.Tables[0].Rows[mDr][0]);
                E[mDr].cd_manufacturer = ds.Tables[0].Rows[mDr][1].ToString();
                E[mDr].cd_name = ds.Tables[0].Rows[mDr][2].ToString();
                E[mDr].cd_preserver = ds.Tables[0].Rows[mDr][3].ToString();
                model.Add(E[mDr]);
            }
            con.Close();
            return View(model);
        }
        public void CreateQrCode()
        {
            string host = Request.Url.Host;
            var port = Request.Url.Port;
            string str = "http://" + host + ":" + port + "/Chemical/ShowChemicalDevice?id=" + Request.Form["qrcode"];
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            con.Open();
            string sqlStr = "select cd_name from dm_chemical_device where id = "+ Request.Form["qrcode"] + ";";
            SqlCommand cmd = new SqlCommand(sqlStr, con);
            string cd_name = cmd.ExecuteScalar().ToString();
            con.Close();
            using (var memoryStream = QRCodeHelper.GetQRCode(str, 10))
            {
                System.Drawing.Image img = Image.FromStream(memoryStream);
                img = QRCodeHelper.AddTextToImg(img, cd_name, cd_name);
                
                System.IO.MemoryStream ms = new System.IO.MemoryStream();
                img.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
                Response.ContentType = "application/octet-stream";
                //文件名+文件格式 （这里编码采用的是utf-8）
                Response.AddHeader("Content-Disposition", "attachment; filename=" + HttpUtility.UrlEncode(cd_name + ".png", System.Text.Encoding.UTF8));
                Response.BinaryWrite(ms.ToArray());
                ms.Dispose();
                img.Dispose();
            }
        }
        public ActionResult AddChemicalDevice()
        {
            return View();

        }
        public JavaScriptResult AddChemicalDevice_Post(chemical_device model)
        {
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            con.Open();
            string sqlStr = "insert into dm_chemical_device(cd_name,cd_model,cd_quantity,cd_num,cd_manufacturer,cd_preserver,cd_begin_time,cd_remark) values('" + model.cd_name + "','" + model.cd_model + "','" + model.cd_quantity + "','" + model.cd_num + "','" + model.cd_manufacturer + "','" + model.cd_preserver + "','" + model.cd_begin_time + "','" + model.cd_remark + "');";
            SqlCommand cmd = new SqlCommand(sqlStr, con);
            int check = cmd.ExecuteNonQuery();
            con.Close();
            if (check == 1)
                return JavaScript("swal_success();jump_ChemicalDeviceList();");
            else
                return JavaScript("swal_error();");
        }
        public ActionResult ModifyChemicalDevice()
        {
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            con.Open();
            string sqlStr = "select cd_name,cd_model,cd_quantity,cd_num,cd_manufacturer,cd_preserver,cd_begin_time,cd_remark from dm_chemical_device where id = " + Request.Form["id"] + ";";
            SqlDataAdapter da = new SqlDataAdapter(sqlStr, con);
            DataSet ds2 = new DataSet();
            da.Fill(ds2);
            chemical_device model = new chemical_device();
            model.cd_name = ds2.Tables[0].Rows[0][0].ToString();
            model.cd_model = ds2.Tables[0].Rows[0][1].ToString();
            model.cd_quantity = Convert.ToInt32(ds2.Tables[0].Rows[0][2]);
            model.cd_num = ds2.Tables[0].Rows[0][3].ToString();
            model.cd_manufacturer = ds2.Tables[0].Rows[0][4].ToString();
            model.cd_preserver = ds2.Tables[0].Rows[0][5].ToString();
            model.cd_begin_time = Convert.ToDateTime(ds2.Tables[0].Rows[0][6]);
            model.cd_remark = ds2.Tables[0].Rows[0][7].ToString();
            model.id = Convert.ToInt32(Request.Form["id"]);
            con.Close();
            return View(model);
        }
        public ActionResult ModifyChemicalDevice_post(chemical_device model)
        {
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            con.Open();
            string sqlStr = "update dm_chemical_device set cd_name = '" + model.cd_name + "' where id = '" + Request.Form["id"] + "';" +
                            "update dm_chemical_device set cd_model = '" + model.cd_model + "' where id = '" + Request.Form["id"] + "';" +
                            "update dm_chemical_device set cd_quantity = '" + model.cd_quantity + "' where id = '" + Request.Form["id"] + "';" +
                            "update dm_chemical_device set cd_num = '" + model.cd_num + "' where id = '" + Request.Form["id"] + "';" +
                            "update dm_chemical_device set cd_manufacturer = '" + model.cd_manufacturer + "' where id = '" + Request.Form["id"] + "';" +
                            "update dm_chemical_device set cd_preserver = '" + model.cd_preserver + "' where id = '" + Request.Form["id"] + "';" +
                            "update dm_chemical_device set cd_begin_time = '" + model.cd_begin_time + "' where id = '" + Request.Form["id"] + "';" +
                            "update dm_chemical_device set cd_remark = '" + model.cd_remark + "' where id = '" + Request.Form["id"] + "';";
            SqlCommand cmd = new SqlCommand(sqlStr, con);
            int check = cmd.ExecuteNonQuery();
            con.Close();
            if (check != 0)
                return JavaScript("swal_success();jump_ChemicalDeviceList();");
            else
                return JavaScript("swal_error();");
        }
        [HttpGet]
        public ActionResult AddChemicalDevicePic(int id)
        {
            ViewBag.cd_id = id;
            List<chemical_device_pic> models = new List<chemical_device_pic>();
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            string sqlStr = "select id,cd_picurl from dm_chemical_device_pic where cd_id = " + ViewBag.cd_id + "; ";
            SqlDataAdapter da = new SqlDataAdapter(sqlStr, con);
            DataSet ds = new DataSet();
            da.Fill(ds);
            chemical_device_pic[] tc = new chemical_device_pic[ds.Tables[0].Rows.Count];
            for (int mDr = 0; mDr < ds.Tables[0].Rows.Count; mDr++)
            {
                tc[mDr] = new chemical_device_pic();
                tc[mDr].id = Convert.ToInt32(ds.Tables[0].Rows[mDr][0]);
                tc[mDr].cd_picurl = ds.Tables[0].Rows[mDr][1].ToString();

                models.Add(tc[mDr]);
            }
            con.Close();
            return View(models);
        }
        [HttpPost]
        public ActionResult AddChemicalDevicePic()
        {
            ViewBag.cd_id = Request.Form["id"];
            List<chemical_device_pic> models = new List<chemical_device_pic>();
            SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["SewagePlantIMS"].ConnectionString);
            string sqlStr = "select id,cd_picurl from dm_chemical_device_pic where cd_id = " + ViewBag.cd_id + "; ";
            SqlDataAdapter da = new SqlDataAdapter(sqlStr, con);
            DataSet ds = new DataSet();
            da.Fill(ds);
            chemical_device_pic[] tc = new chemical_device_pic[ds.Tables[0].Rows.Count];
            for (int mDr = 0; mDr < ds.Tables[0].Rows.Count; mDr++)
            {
                tc[mDr] = new chemical_device_pic();
                tc[mDr].id = Convert.ToInt32(ds.Tables[0].Rows[mDr][0]);
                tc[mDr].cd_picurl = ds.Tables[0].Rows[mDr][1].ToString();

                models.Add(tc[mDr]);
            }
            con.Close();
            return View(models);
        }
        public void AddChemicalDevicePicPost()
        {
            chemical_device_pic ep = new chemical_device_pic();
            HttpPostedFileBase ff = Request.Files["File"];

            /*if (ff != null && ff.ContentLength != 0)
             {
                 if (!Directory.Exists(Server.MapPath("~images/ElectricalPic")))
                 {
                     Directory.CreateDirectory("~images/ElectricalPic");
                 }
             }*/
            //修改文件名去掉其原有的扩展名
            string filename = Request.Form["filename2"];
            string[] filename_temp = filename.Split('.');
            filename = filename_temp[0];
            //读取elec_pic表最后一个id号加1最为不重复图片名的依据

SewagePlantIMS/SewagePlantIMS/Views/Chemical/AddChemicalDevice.cshtml
@model SewagePlantIMS.Models.chemical_device

@{
    ViewBag.Title = "添加仪表信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<fieldset>
    <legend style="color:#5b9bd1">添加仪表信息</legend>
</fieldset>

@using (Ajax.BeginForm("AddChemicalDevice_Post", "Chemical", new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,

}))
{

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_name, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_name, new { htmlAttributes = new { @class = "form-control" ,@placeholder="请输入仪器名称"}})
            @Html.ValidationMessageFor(model => model.cd_name, "", new { @class = "text-danger" })
        </div>

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_model, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_model, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入仪器型号" } })
            @Html.ValidationMessageFor(model => model.cd_model, "", new { @class = "text-danger" })

        </div>

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_quantity, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_quantity, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入仪器数量" } })
            @Html.ValidationMessageFor(model => model.cd_quantity, "", new { @class = "text-danger" })

        </div>

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_num, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_num, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入仪器编号" } })
            @Html.ValidationMessageFor(model => model.cd_num, "", new { @class = "text-danger" })
        </div>

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_manufacturer, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_manufacturer, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入厂家名称" } })
            @Html.ValidationMessageFor(model => model.cd_manufacturer, "", new { @class = "text-danger" })
        </div>

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_preserver, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_preserver, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入保管人" } })
            @Html.ValidationMessageFor(model => model.cd_preserver, "", new { @class = "text-danger" })
        </div>

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_begin_time, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_begin_time, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入启用时间", type = "date" } })
            @Html.ValidationMessageFor(model => model.cd_begin_time, "", new { @class = "text-danger" })

        </div>

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_remark, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_remark, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入其他需要补充的信息" }  })
            @Html.ValidationMessageFor(model => model.cd_remark, "", new { @class = "text-danger" })
        </div>
        
            <button type="submit" class="btn btn-primary btn-block">添加仪器</button>
           

}
<button class="btn btn-default btn-block" onclick="javascrtpt: window.location.href = 'ChemicalDeviceList'">返回</button>

SewagePlantIMS/SewagePlantIMS/Views/Chemical/AddChemicalDevicePic.cshtml
@model List<SewagePlantIMS.Models.chemical_device_pic>
@{
    ViewBag.Title = "添加化验仪器图片";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">

    $(function () {
        $('#sub').click(function () {
            if ($("#filename").text() == '') {
                document.getElementById('fileerrorTip1').innerHTML = '您未选取任何需要要添加的图片！！';
                document.getElementById('fileerrorTip1').style.color = "red";
                return false;
            }
        });
    });
    /*function imgUrl() {
        document.getElementById("imgInit").src = "/images/ElectricalPic/电脑性能测试.png";
    }*/
</script>

<fieldset>
    <legend style="color:#5b9bd1">添加仪器图片</legend>
</fieldset>
<div class="row">
    @foreach (var item in Model)
    {

        <div class="col-md-3">
            <div class="thumbnail">
                <img src=@item.cd_picurl id="imgInit" onerror="imgUrl()" width="100" height="100" />


                <div class="caption">
                    @using (@Html.BeginForm("DeletePic", "Chemical", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                        <center><p><button href="" class="btn btn-danger" role="button" value=@item.id name="del_id">删除</button></p></center>
                    }
                </div>
            </div>
        </div>

    }
</div>

<hr />
@using (@Html.BeginForm("ElectricalPicPost", "Chemical", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <!--<input id="File1" type="file" name="File"/>-->
    <table>
        <tr>
            <td>
                <a class="input-file input-fileup" href="javascript:;">
                    + 选择文件<input size="100" type="file" name="file" id="file">
                </a>
            </td>
            <td>
                <button type="submit" value="@ViewBag.cd_id" name="id" class="btn btn-default btn-sm" id="sub">提交图片</button>
            </td>
        </tr>
    </table>

    <div class="fileerrorTip1" id="fileerrorTip1"></div>
    <div class="showFileName1" id="filename"></div>
    <input type="text" name="filename2" style="visibility: hidden;" id="filename2" />
}

SewagePlantIMS/SewagePlantIMS/Views/Chemical/ChemicalDeviceList.cshtml
@model List<SewagePlantIMS.Models.chemical_device>
@{
    ViewBag.Title = "化验室仪器清单";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int num = 1;
}

<fieldset>
    <legend style="color:#5b9bd1">化验室仪器清单</legend>
</fieldset>

<a href="AddChemicalDevice">新增仪器信息</a>
<table class="table table-bordered table-hover table-striped" id="table_id_example">
    <thead>
        <tr>
            <th>序号</th>
            <th>厂家</th>
            <th>仪器名称</th>
            <th>保管人</th>
            <th>相关操作</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </tfoot>
    <tbody>
        @foreach (var item in Model)
            {
            <tr>
                <td>@num</td>
                <td>@item.cd_manufacturer </td>
                <td>@item.cd_name</td>
                <td>@item.cd_preserver</td>
                <td>
                    @using (@Html.BeginForm("ModifyChemicalDevice", "Chemical", FormMethod.Post, new { @class = "myform" }))
                    {
                        <button class="btn btn-success btn-xs" type="submit" value="@item.id" name="id">修改</button>
                    }
                    @using (@Html.BeginForm("AddChemicalDevicePic", "Chemical", FormMethod.Post, new { @class = "myform" }))
                    {
                        <button class="btn btn-primary btn-xs" type="submit" value="@item.id" name="id">添加图片</button>
                    }
                    @using (Ajax.BeginForm("DeleteChemicalDevice", "Chemical", new AjaxOptions
                    {
                        HttpMethod = "POST",
                        InsertionMode = InsertionMode.Replace,
                    }, new { @class = "myform" }))
                    {
                        <button class="btn btn-danger btn-xs" type="submit" value="@item.id" name="del" id="del" onclick="return confirm('确定删除吗？？？')">删除</button>
                    }
                    @using (@Html.BeginForm("ShowChemicalDevice", "Chemical", FormMethod.Post, new { @class = "myform" }))
                    {
                        <button class="btn btn-default btn-xs" value="@item.id" name="show">展示页</button>
                    }
                    @using (@Html.BeginForm("CreateQRcode", "Chemical", FormMethod.Post, new { @class = "myform" }))
                    {
                        <button class="btn btn-warning btn-xs" value="@item.id" name="qrcode" type="submit">二维码</button>
                    }
                </td>
            </tr>
            num++;
        }

    </tbody>

</table>

SewagePlantIMS/SewagePlantIMS/Views/Chemical/ModifyChemicalDevice.cshtml
@model SewagePlantIMS.Models.chemical_device
@{
    ViewBag.Title = "修改仪器信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<fieldset>
    <legend style="color:#5b9bd1">修改仪器信息</legend>
</fieldset>

@using (Ajax.BeginForm("ModifyChemicalDevice_Post", "Chemical", new AjaxOptions
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,

}))
{

    <div class="am-form-group">
        @Html.LabelFor(model => model.cd_name, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.cd_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入仪器名称" } })
        @Html.ValidationMessageFor(model => model.cd_name, "", new { @class = "text-danger" })
    </div>

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_model, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_model, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入仪器型号" } })
            @Html.ValidationMessageFor(model => model.cd_model, "", new { @class = "text-danger" })

        </div>

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_quantity, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_quantity, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入仪器数量" } })
            @Html.ValidationMessageFor(model => model.cd_quantity, "", new { @class = "text-danger" })

        </div>

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_num, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_num, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入仪器编号" } })
            @Html.ValidationMessageFor(model => model.cd_num, "", new { @class = "text-danger" })
        </div>

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_manufacturer, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_manufacturer, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入厂家名称" } })
            @Html.ValidationMessageFor(model => model.cd_manufacturer, "", new { @class = "text-danger" })
        </div>

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_preserver, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_preserver, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入保管人" } })
            @Html.ValidationMessageFor(model => model.cd_preserver, "", new { @class = "text-danger" })
        </div>

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_begin_time, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_begin_time, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入启用时间", @type = "datetime"  } })
            @Html.ValidationMessageFor(model => model.cd_begin_time, "", new { @class = "text-danger" })
        </div>

        <div class="am-form-group">
            @Html.LabelFor(model => model.cd_remark, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.cd_remark, new { htmlAttributes = new { @class = "form-control", @placeholder = "请输入其他需要补充的信息" } })
            @Html.ValidationMessageFor(model => model.cd_remark, "", new { @class = "text-danger" })
        </div>

        <button type="submit" class="btn btn-primary btn-block" name="id" value="@Model.id">修改仪器</button>


}
<button class="btn btn-default btn-block" onclick="javascrtpt: window.location.href = 'ChemicalDeviceList'">返回</button>

SewagePlantIMS/SewagePlantIMS/Views/Chemical/ShowChemicalDevice.cshtml
@model List<SewagePlantIMS.ViewModels.ShowChemicalDevice>
@{
    Layout = null;
    int i = 0;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>化验室仪器</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


    <style>
        .carousel .item {
            height: 400px;
            background-color: #777;
        }

        .carousel-inner > .item > img {
            position: absolute;
            top: 0;
            left: 0;
            min-width: 100%;
            height: 400px;
        }
    </style>
</head>
<body>

    <div id="myCarousel" class="carousel slide">

        <div class="carousel-inner">
            @foreach (var item in Model)
            {
                if (@i == 0)
                {
                    <div class="item active">
                        <img src=@item.cd_picurl onclick="showMaxImg(this)">
                    </div>
                }
                else
                {
                    <div class="item">
                        <img src=@item.cd_picurl onclick="showMaxImg(this)">
                    </div>
                }
                i++;
            }

        </div>
        <!-- 轮播（Carousel）导航 -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    @foreach (var item in Model)
    {
        <table class="table">
            <tr>
                <td style="width:100px">仪器名称：</td>
                <td>@item.cd_name</td>
            </tr>
            <tr>
                <td>型号：</td>
                <td>@item.cd_model</td>
            </tr>
            <tr>
                <td>数量：</td>
                <td>@item.cd_quantity</td>
            </tr>
            <tr>
                <td>出厂编号：</td>
                <td>@item.cd_num</td>
            </tr>
            <tr>
                <td>厂家：</td>
                <td>@item.cd_manufacturer</td>
            </tr>
            <tr>
                <td>保管人：</td>
                <td>@item.cd_preserver</td>
            </tr>
            <tr>
                <td>启用时间：</td>
                <td>@item.cd_begin_time.ToShortDateString()</td>
            </tr>
            <tr>
                <td>备注：</td>
                <td>@item.cd_remark</td>
            </tr>
        </table>
        break;
    }
    <div class="modal fade bs-example-modal-lg text-center" id="imgModal" tabindex="-1" role="dialog" data-toggle="modal" aria-labelledby="myLargeModalLabel" aria-hidden="true">   <div class="modal-dialog modal-lg" style="display:inline-block;width:auto;">       <div class="modal-content">           <div id="imgshow"></div>        </div>      </div>    </div>

</body>
</html>

<script>
    $(function () {
        $('#myCarousel').carousel({
            interval: 3000
        });
    });
    function showMaxImg(obj) { var src = $(obj).attr("src"); $("#imgModal").find("#imgshow").html("<img src='" + src + "' class='carousel-inner img-responsive img-rounded' data-dismiss='modal'>"); $("#imgModal").modal('show'); }

</script>